using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Monowakaru.Languages.Generators.Diagnostics;
using Monowakaru.Languages.Generators.GenerationTargets;

namespace Monowakaru.Languages.Generators.SourceProviders;

public static class RuleTableSourceProvider
{
    public static GenerationResult GetImplementationSource(RuleTableGenerationTarget target)
    {
        var baseNames = ComputeUniqueRecordBaseNames(target.RuleGenerationTargets).ToImmutableArray();
        var namedTargets = target.RuleGenerationTargets
            .Zip(baseNames, (t, name) => new NamedRuleTarget(t, name))
            .ToImmutableArray();

        return GetRuleImplementationRecords(namedTargets).Map(records =>
        {
            var backing = GetBackingDataAndLookup(namedTargets);
            return $$"""
                     // <auto-generated/>
                     #nullable enable

                     using System;
                     using System.Collections.Frozen;
                     using System.Collections.Generic;
                     using Monowakaru.Languages.Grammar;
                     using Monowakaru.Languages.Grammar.Inflection;

                     namespace {{target.Namespace}};

                     public sealed partial class {{target.ClassName}} : IRuleSet
                     {
                     {{Indent(records, 4)}}

                     {{Indent(backing, 4)}}
                     }
                     """;
        });
    }

    private static GenerationResult GetRuleImplementationRecords(ImmutableArray<NamedRuleTarget> namedTargets)
    {
        return namedTargets
            .Select(nt => GetRuleImplementationRecord(nt.Target, nt.BaseName))
            .JoinResults("\n\n");
    }

    private static GenerationResult GetRuleImplementationRecord(RuleGenerationTarget target, string recordBaseName)
    {
        return target switch
        {
            SuffixRuleGenerationTarget s => SuffixRuleSourceProvider.GetImplementationSource(s, recordBaseName),
            _ => GenerationResult.Fail(GeneratorDiagnostics.UnknownRuleType, Location.None, target.GetType().Name)
        };
    }

    private static string GetBackingDataAndLookup(ImmutableArray<NamedRuleTarget> namedTargets)
    {
        var suffixTargets = namedTargets
            .Where(nt => nt.Target is SuffixRuleGenerationTarget)
            .Select(nt => new NamedSuffixTarget((SuffixRuleGenerationTarget)nt.Target, nt.BaseName))
            .ToImmutableArray();

        var inflectionInstances = suffixTargets.Select(t => $"{t.BaseName}Inflection.Instance").ToImmutableArray();
        var deinflectionInstances = suffixTargets.Select(t => $"{t.BaseName}Deinflection.Instance").ToImmutableArray();

        var inflectionGroups = suffixTargets
            .GroupBy(t => t.Target.InputSuffix)
            .OrderByDescending(g => g.Key.Length)
            .ToImmutableArray();

        var deinflectionGroups = suffixTargets
            .GroupBy(t => t.Target.OutputSuffix)
            .OrderByDescending(g => g.Key.Length)
            .ToImmutableArray();

        var maxInflectionLen = inflectionGroups.Length == 0 ? 0 : inflectionGroups.Max(g => g.Key.Length);
        var maxDeinflectionLen = deinflectionGroups.Length == 0 ? 0 : deinflectionGroups.Max(g => g.Key.Length);

        var inflectionIndexEntries = string.Join("\n        ", inflectionGroups.Select(g =>
            $"[\"{EscapeKey(g.Key)}\"] = new IInflectionRule[] {{ {string.Join(", ", g.Select(t => $"{t.BaseName}Inflection.Instance"))} }},"));
        var deinflectionIndexEntries = string.Join("\n        ", deinflectionGroups.Select(g =>
            $"[\"{EscapeKey(g.Key)}\"] = new IDeinflectionRule[] {{ {string.Join(", ", g.Select(t => $"{t.BaseName}Deinflection.Instance"))} }},"));

        var inflectionArrayLiteral = inflectionInstances.Length == 0
            ? "global::System.Array.Empty<IInflectionRule>()"
            : $"new IInflectionRule[] {{ {string.Join(", ", inflectionInstances)} }}";
        var deinflectionArrayLiteral = deinflectionInstances.Length == 0
            ? "global::System.Array.Empty<IDeinflectionRule>()"
            : $"new IDeinflectionRule[] {{ {string.Join(", ", deinflectionInstances)} }}";

        return $$"""
                 private static readonly IInflectionRule[] _inflectionRules = {{inflectionArrayLiteral}};

                 private static readonly IDeinflectionRule[] _deinflectionRules = {{deinflectionArrayLiteral}};

                 private static readonly FrozenDictionary<string, IInflectionRule[]> _inflectionIndex =
                     new Dictionary<string, IInflectionRule[]>(StringComparer.Ordinal)
                     {
                         {{inflectionIndexEntries}}
                     }.ToFrozenDictionary(StringComparer.Ordinal);

                 private static readonly FrozenDictionary<string, IDeinflectionRule[]> _deinflectionIndex =
                     new Dictionary<string, IDeinflectionRule[]>(StringComparer.Ordinal)
                     {
                         {{deinflectionIndexEntries}}
                     }.ToFrozenDictionary(StringComparer.Ordinal);

                 private const int _maxInflectionSuffixLength = {{maxInflectionLen}};
                 private const int _maxDeinflectionSuffixLength = {{maxDeinflectionLen}};

                 public IReadOnlyList<IInflectionRule> InflectionRules => _inflectionRules;
                 public IReadOnlyList<IDeinflectionRule> DeinflectionRules => _deinflectionRules;

                 public IReadOnlyList<InflectionResult> Inflect(string term)
                 {
                     if (string.IsNullOrEmpty(term)) return Array.Empty<InflectionResult>();
                     List<InflectionResult>? results = null;
                     var alt = _inflectionIndex.GetAlternateLookup<ReadOnlySpan<char>>();
                     var max = Math.Min(_maxInflectionSuffixLength, term.Length);
                     for (var len = 1; len <= max; len++)
                     {
                         var span = term.AsSpan(term.Length - len);
                         if (!alt.TryGetValue(span, out var rules)) continue;
                         results ??= new List<InflectionResult>(rules.Length);
                         foreach (var rule in rules)
                             results.Add(new InflectionResult(rule, rule.Apply(term)));
                     }
                     return (IReadOnlyList<InflectionResult>?)results ?? Array.Empty<InflectionResult>();
                 }

                 public IReadOnlyList<DeinflectionResult> Deinflect(string term)
                 {
                     if (string.IsNullOrEmpty(term)) return Array.Empty<DeinflectionResult>();
                     List<DeinflectionResult>? results = null;
                     var alt = _deinflectionIndex.GetAlternateLookup<ReadOnlySpan<char>>();
                     var max = Math.Min(_maxDeinflectionSuffixLength, term.Length);
                     for (var len = 1; len <= max; len++)
                     {
                         var span = term.AsSpan(term.Length - len);
                         if (!alt.TryGetValue(span, out var rules)) continue;
                         results ??= new List<DeinflectionResult>(rules.Length);
                         foreach (var rule in rules)
                             results.Add(new DeinflectionResult(rule, rule.Apply(term)));
                     }
                     return (IReadOnlyList<DeinflectionResult>?)results ?? Array.Empty<DeinflectionResult>();
                 }
                 """;
    }

    private static IEnumerable<string> ComputeUniqueRecordBaseNames(ImmutableArray<RuleGenerationTarget> targets)
    {
        var baseNames = targets.Select(GetBaseNameForTarget).ToList();
        var counts = baseNames.GroupBy(n => n).ToDictionary(g => g.Key, g => g.Count());
        var counters = new Dictionary<string, int>();

        return baseNames.Select(name =>
        {
            if (counts[name] == 1) return name;
            counters.TryGetValue(name, out var i);
            counters[name] = i + 1;
            return $"{name}{i}";
        });
    }

    private static string GetBaseNameForTarget(RuleGenerationTarget target)
    {
        return target switch
        {
            SuffixRuleGenerationTarget s => GetFormName(s.Form),
            _ => target.GetType().Name
        };
    }

    private static string GetFormName(string form)
    {
        var lastDot = form.LastIndexOf('.');
        return lastDot >= 0 ? form[(lastDot + 1)..] : form;
    }

    private static string EscapeKey(string key)
    {
        return key.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string Indent(string source, int spaces)
    {
        var pad = new string(' ', spaces);
        return string.Join("\n", source.Split('\n').Select(line => line.Length == 0 ? line : pad + line));
    }

    private sealed record NamedRuleTarget(RuleGenerationTarget Target, string BaseName);

    private sealed record NamedSuffixTarget(SuffixRuleGenerationTarget Target, string BaseName);
}