using Microsoft.CodeAnalysis;

namespace Monowakaru.Languages.Generators;

/// <summary>
///     Emits the <see cref="Attributes.InflectionTableAttribute" /> and
///     <see cref="Attributes.SuffixRuleAttribute" /> source into consuming compilations via
///     <see cref="IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput" />.
///     Consumers therefore do not need an assembly reference to the generator project to use the
///     attributes — the generator is referenced as an analyzer only.
/// </summary>
/// <remarks>
///     The shapes emitted here MUST match the generator-side attribute classes in
///     <c>Attributes/SuffixRuleAttribute.cs</c> and <c>Attributes/InflectionTableAttribute.cs</c>,
///     because <c>RuleTableGenerator</c> reads them from consumer compilations using the same
///     <c>typeof(...).FullName</c> as the generator-side classes. Adding a property here also
///     requires reading it back in <c>RuleTableGenerator</c>'s extraction.
/// </remarks>
[Generator]
public class AttributeSourceGenerator : IIncrementalGenerator
{
    private const string InflectionTableAttributeSource =
        """
        // <auto-generated/>
        #nullable enable

        namespace Monowakaru.Languages.Generators.Attributes;

        /// <summary>
        ///     Marks a partial class as an inflection rule table. All <c>SuffixRuleAttribute</c>s on the
        ///     class contribute records to the generated implementation, and the class itself receives
        ///     a generated <c>IRuleSet</c> body.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        internal sealed class InflectionTableAttribute : global::System.Attribute
        {
            /// <summary>CSV of condition IDs used as <c>SuffixRuleAttribute.Accepts</c> when a rule omits its own.</summary>
            public string DefaultAccepts { get; init; } = "";

            /// <summary>CSV of condition IDs used as <c>SuffixRuleAttribute.Produces</c> when a rule omits its own.</summary>
            public string DefaultProduces { get; init; } = "";
        }
        """;

    private const string SuffixRuleAttributeSource =
        """
        // <auto-generated/>
        #nullable enable

        namespace Monowakaru.Languages.Generators.Attributes;

        /// <summary>
        ///     Declares one suffix-swap rule pair within a class marked with <c>InflectionTableAttribute</c>.
        ///     The deinflection inverse is generated automatically by swapping suffixes and accepts/produces.
        /// </summary>
        /// <remarks>
        ///     <para>
        ///         <c>Accepts</c> and <c>Produces</c> describe the rule in the inflection direction.
        ///         The deinflection inverse uses <c>Produces</c> as its accepts and <c>Accepts</c> as its produces.
        ///     </para>
        ///     <para>
        ///         CSV strings are comma-separated condition IDs (e.g. <c>"v5"</c> or <c>"v5,v5k"</c>);
        ///         whitespace is trimmed. Empty strings inherit table-level defaults from
        ///         <c>InflectionTableAttribute.DefaultAccepts</c> / <c>DefaultProduces</c>.
        ///     </para>
        /// </remarks>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        internal sealed class SuffixRuleAttribute : global::System.Attribute
        {
            public SuffixRuleAttribute(string inputSuffix, string outputSuffix, string form)
            {
                InputSuffix = inputSuffix;
                OutputSuffix = outputSuffix;
                Form = form;
            }

            public string InputSuffix { get; }
            public string OutputSuffix { get; }
            public string Form { get; }

            /// <summary>CSV of accepts condition IDs (inflection direction).</summary>
            public string Accepts { get; init; } = "";

            /// <summary>CSV of produces condition IDs (inflection direction).</summary>
            public string Produces { get; init; } = "";
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("InflectionTableAttribute.g.cs", InflectionTableAttributeSource);
            ctx.AddSource("SuffixRuleAttribute.g.cs", SuffixRuleAttributeSource);
        });
    }
}