using Microsoft.CodeAnalysis;

namespace Monowakaru.Languages.Generators;

/// <summary>
///     Emits the <see cref="Attributes.InflectionTableAttribute" /> and
///     <see cref="Attributes.SuffixRuleAttribute" /> source into consuming compilations via
///     <see cref="IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput" />.
///     Consumers therefore do not need an assembly reference to the generator project to use the
///     attributes — the generator is referenced as an analyzer only.
/// </summary>
[Generator]
public class AttributeSourceGenerator : IIncrementalGenerator
{
    private const string InflectionTableAttributeSource =
        """
        // <auto-generated/>
        #nullable enable

        namespace Monowakaru.Languages.Generators.Attributes;

        /// <summary>
        ///     Marks a partial class as an inflection rule table. All implementations of
        ///     <see cref="SuffixRuleAttribute" /> on the class will be emitted in this class.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        internal sealed class InflectionTableAttribute : global::System.Attribute;
        """;

    private const string SuffixRuleAttributeSource =
        """
        // <auto-generated/>
        #nullable enable

        namespace Monowakaru.Languages.Generators.Attributes;

        /// <summary>
        ///     Declares one suffix-swap rule pair within a class marked with
        ///     <see cref="InflectionTableAttribute" />.
        /// </summary>
        /// <param name="inputSuffix">
        ///     Suffix on the dictionary / base form that this rule applies to.
        /// </param>
        /// <param name="outputSuffix">
        ///     Suffix that replaces <paramref name="inputSuffix" /> after inflection.
        /// </param>
        /// <param name="form">
        ///     Fully-qualified path to a static <c>IInflectionForm</c> property,
        ///     e.g. <c>"JapaneseForms.TeForm"</c>. Emitted verbatim in the generated code.
        /// </param>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        internal sealed class SuffixRuleAttribute : global::System.Attribute
        {
            public SuffixRuleAttribute(string inputSuffix, string outputSuffix, string form)
            {
                InputSuffix = inputSuffix;
                OutputSuffix = outputSuffix;
                Form = form;
            }

            public string InputSuffix { get; }
            public string OutputSuffix { get; }
            public string Form { get; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("InflectionTableAttribute.g.cs", InflectionTableAttributeSource);
            ctx.AddSource("SuffixRuleAttribute.g.cs", SuffixRuleAttributeSource);
        });
    }
}